### ISSUE TITLE
HTTP Error

### ISSUE THREAD

**Issue by Bagel94** [ChurchApps/FreeShow#1593]
Just update to the 1.4.2 version and have been testing out the CHUMS syncing. So, I assume this has something to do with FreeShow not finding anything to pull from CHUMS?

![Image](https://github.com/user-attachments/assets/8357b3a7-7f68-4882-a48e-f7e6b8110417)

**Comment by vassbo** [comment]
I suppose so, please let me know how it works if you create a sermon project in Chums.

**Comment by Bagel94** [comment]
@vassbo just made a quick service order in Chums with just 2 songs, and FreeShow pulled that data in, then proceeded to give the http error.

Could it be possible it's caused by the syncing of the song library to CHUMS? We've got like 758 songs in FreeShow, but only around 50 showed up in CHUMS. Of the one's that did sync, their metadata is not constant between them. Some have no metadata, a bit of data, and others have the title, author, copyright, year, and ccli #.

**Comment by vassbo** [comment]
Maybe..

@jzongker Would you like to check this out?

**Comment by Bagel94** [comment]
As I've been playing around in the order of service trying to learn it a bit more and doing syncs in FreeShow, more songs have started to show up in CHUMS.

Not sure if this is the place for it, but when I title something in CHUMS with a scripture, says Genesis 1:1 it gets loaded into FreeShow as Genesis 11. (see image)

![Image](https://github.com/user-attachments/assets/98acbf3f-257d-48e6-bf23-f70595cc8a31)

**Comment by vassbo** [comment]
Nice.

The name is because `:` is not allowed in filenames!
![Image](https://github.com/user-attachments/assets/644bf70e-1072-40cf-a6cc-07934a0c003b)

**Comment by Bagel94** [comment]
Okay, that makes sense now. Thanks for the clarification! Hmm, this is probably more of a CHUMS issue log, but would it be possible for them to add a scripture item in the service order?

The library sync still isn't the whole library, but I did see 2 popups in the corner saying that 360 were synced and 340 were synced, after clicking sync to CHUMS. Though I don't think all those have showed up in CHUMS yet.

**Comment by vassbo** [comment]
Sounds like some songs at a time are syncing. It might be rate limited, and just stopping on that error each time, instead of retrying.. But I'm not sure.

For the scripture item, I'll let @jzongker decide, might be too much work.

**Comment by vassbo** [comment]
@Bagel94 How is this in the latest update (1.4.3)?

**Comment by Bagel94** [comment]
@vassbo no longer getting the HTTP Error warning, but I created a new test service order in CHUMS which FreeShow imported, but I made some updates to it and now FreeShow is not pulling anything in from CHUMS at all, even after trying to create a whole new service order. 

@jzongker Also, when checking the song list, some songs have now been duplicated 2 to 3 times.

**Comment by jzongker** [comment]
@Bagel94 - That's no good.  Is is just a handful of songs getting duplicated while the others don't?  Does it consistently make another copy every time you open FreeShow?

**Comment by Bagel94** [comment]
@jzongker I don't think it's every time FreeShow opens. I've not been able to gets any service schedules from CHUMS since after the first-time opening version 1.4.3. But it's only some of the songs, not all.

![Image](https://github.com/user-attachments/assets/15396ec7-b444-4ed3-b588-05e3ebdc391f)

Though I have noticed that when left unopen for a while, FreeShow does ask for permission to access CHUMS again, is this the intended action that it's meant to do? I have also noticed that it seems to be opening 2 tabs to get access, where the second one opens after the agreeing to the first one, but when you select your church to pull from it just gives a localhost error.

![Image](https://github.com/user-attachments/assets/c113a76b-7180-4d0b-8dea-ba2054d2100d)

**Comment by jzongker** [comment]
@Bagel94 - Thank you!

**Issue #1 (Duplicate Songs)** - I believe this is resolved, but was never able to fully reproduce it.  I've cleaned up all of the existing duplicated song records.  Let me know if they keep duplicating.

**Issue #2 (Schedule not importing)** - This is fixed on the dev branch and should be good again with the next update.  https://github.com/ChurchApps/FreeShow/commit/6686a5373469f14a362fc3b1f923ad5cca3f3007  

**Issue #3 (Login popups)** - The access token expires after 12 hours and is supposed to be auto-refreshed in the background.  This wasn't working right in 1.4.2 but is in 1.4.3.  I think the multiple windows may be from opening and closing the app multiple times during testing without completing that log in.  I think the "Can't reach this page" error message was likely because FreeShow was no longer open when you did complete the login.  If you close all the windows, open FreeShow and login, I think everything will be back to normal.

**Comment by Bagel94** [comment]
@jzongker Thanks for the update, I'll keep testing some more once the next update rolls around.

Thanks to you and @vassbo for all your work, it's greatly appreciated!

**Comment by jzongker** [comment]
@Bagel94 - Yes.  I've updated the notification to display the number of services imported and the number of songs exported (which should be 0 if you haven't added any recently).  

There's also some error logging in place with the last update that we can take a look at if these fixes don't get the job done.  (Settings->Other->Open error log)

**Comment by vassbo** [comment]
@Bagel94 Try this: https://github.com/ChurchApps/FreeShow/releases/tag/v1.4.4-beta.1

**Comment by Bagel94** [comment]
Out of curiosity, does the sync with Chums only pull things current and previous? Say if I set a service date for June 8th, would that sync into FreeShow?

Not getting any error that I've noticed. Unless it's a little slow, I have not seen any more songs get added to the Chums library.

Think I seen somewhere else that it mostly pulls from the songs label, from the shows tab? If that's the case, still missing about 300 songs. Unless it's having a hard time matching Hymns? Which would make up the bulk of the library.

**Comment by vassbo** [comment]
@Bagel94 It only syncs the songs you have in a service plan! So unless you have the missing 300 in a service that is synced it's working as it should.

It should sync all the service plans from max one week ahead of time.

**Comment by Bagel94** [comment]
@vassbo my bad, I forgot to tag @jzongker on that last bit. In referring to syncing the songs from FreeShow to Chums. I recall seeing the popup that ~360 ish songs were synced, but they never populated in Chums.

**Comment by vassbo** [comment]
Got it! You were talking about pushing the songs from FreeShow to Chums. Did you try disconnecting fully in the settings, closing the app, and then reconnecting again?

**Comment by jzongker** [comment]
@Bagel94 - Would you mind telling me what the name of the church is you're trying to sync to in Chums?  Those 360 song records got saved somewhere if you got the confirmation.   I'll try tracking them down.  If there are any super uncommon song titles I could search for that would help.

**Comment by jzongker** [comment]
@Bagel94 - Never mind on my previous question.  I was able to find the church (Dover) and what's synced so far based on your screenshot above.  To answer your other questions.

**Schedules:** Chums->FreeShow - It will only sync the next upcoming show.  It will not sync a past show.
**Songs:** FreeShow->Chums - It will (should) sync everything in the "Songs" category.
**Hymns:** Syncing shouldn't be an issue.  If it can't find a match from PraiseCharts it still creates a song record with the lyrics you have.

Let's try this.  Can you go to Settings->Other and click "Open user data folder" in the bottom right corner?  There's a folder of Shows in there.  Can you grab the .show file for one that is failing to import and attach it here?  You'll need to rename it from .show to .json for GitHub to allow it.  I'll try importing that and see if I can get it to fail.

**Comment by jzongker** [comment]
@Bagel94 - Thank you.  Pretty sure I see the issue.  I set up the sync to only check the default "Songs" category, so that it doesn't sync announcements, sermon notes, etc.  It looks like these songs are in an Open LP category instead so they were being missed.  I'll update the sync settings to allow you to select which categories to sync.

**Comment by Bagel94** [comment]
@jzongker wow, that's actually interesting, as there isn't an OpenLP category?

![Image](https://github.com/user-attachments/assets/545666a4-b4e9-4048-828d-d4a0fd113b3b)

Wonder if that something left over from when we first started using FreeShow and imported everything in from OpenLP...

**Comment by vassbo** [comment]
@Bagel94 I'm guessing you have just renamed the original "OpenLP" category to e.g. "Nipgen Imports".

**Comment by Bagel94** [comment]
@vassbo no, the nipgen category is its own thing, and was added way after importing files from OpenLP.

**Comment by jzongker** [comment]
@Bagel94 - Could you try something for me?  With one of the songs that hasn't synced, drag it to another folder, then drag it back to Songs.  Relaunch FreeShow and see if that triggers that one to sync.

**Comment by Bagel94** [comment]
Well, I would but started getting an HTTP Error: 400 this morning when I went to try what you suggested....

![Image](https://github.com/user-attachments/assets/124d9d6f-a56c-432e-9887-518bc1500ed0)

**Comment by jzongker** [comment]
@Bagel94 - I'm pretty sure it logged you out again.  Connecting it to chums again should fix that error.  I had the hardest time getting the oAuth renewal tokens to work right, but so far everything appears good in the current dev build. 

So, I *think* I finally know what happened.  I suspect the songs were originally imported to an "OpenLP" folder.  That folder was later renamed to just "Songs", but still has it's original id of "openlp", which is why the current import isn't finding those songs.  The next release will allow you to select which categories to import, which should solve this.  Sorry it's taken a while to get this resolved.  https://github.com/ChurchApps/FreeShow/pull/1688

**Comment by vassbo** [comment]
@Bagel94 You can download version 1.4.5-beta.1 to test it out.

Some other people also got the 400:
![Image](https://github.com/user-attachments/assets/4d1e4ec2-ca71-4148-86f8-58615fefa459)

**Comment by Bagel94** [comment]
@vassbo hey, I did give the new beta a test and we're still getting this error:

![Image](https://github.com/user-attachments/assets/498b8a31-215a-4a90-8770-0f4e3ca2cba7)

and the error from my previous post when trying to click connect to chums in settings. Which keeps asking me to sign out and back in.. though that hasn't worked. Wonder if clearing browser cache is needed?

**Comment by jzongker** [comment]
@Bagel94 - I was able to reproduce both of these.  There were two issues:

1. There was an API bug that caused it to issue the first refresh token ok, but next time when it tries to get a refresh token the second time, it would fail.    This is fixed in production now.  I shortened the timeout on staging and tested refreshing a dozen times just to be sure. :-)  This caused the 400 error above.
2. Whenever the token got in this invalid state, it wasn't being removed from the cache in FreeShow.  When you tried to authenticate again, it would try to use that bad token again and give you that not authorized message.  This is fixed in development and will be in the next release.

No need to do anything on your end.  Hopefully these are the last of the issues.

**Comment by Bagel94** [comment]
@jzongker okay, thanks for the update. I'm testing out what you asked me to do a few posts back.

Trying to move one of the songs that won't sync to a different category and then moving it back into songs. I'll also check the .show file to see if it still has it listed as "OpenLP". Edit: After exporting the show file and looking at it, it is now listed as "category":"song".... which I thought might cause an issue, but I checked one of the songs that has synced to Chums, and it also is listed as "category":"song". So, I guess at this point just waiting for it to sync up.

In the middle of testing, this popped up a couple of times:

![Image](https://github.com/user-attachments/assets/aadd5f65-b9ac-4a6a-a220-9063884eb171)

**Comment by jzongker** [comment]
I think that 502 error is a symptom of the same bad auth token problem.

v1.4.5 is available now which has the options to select categories to sync, so no need to mess with moving the songs between categories now.  Disconnect and reconnect to chums once you have it and then go into the settings and pick the folder(s) to sync.  Hopefully everything just works from that point forward.

**Comment by jzongker** [comment]
@Bagel94 - Did 1.4.5 fix the problem?

**Comment by vassbo** [comment]
![Image](https://github.com/user-attachments/assets/f50be14b-2b9d-496f-b628-0b8698618f4f)

**Comment by Bagel94** [comment]
@jzongker sorry, been a busy weekend. I'll get it updated and give it a shot.

**Comment by Bagel94** [comment]
When I go to authorize free show to use chums, it just says "loading" and clicking allow does nothing.

![Image](https://github.com/user-attachments/assets/09a5926f-d037-4341-add4-11083e84e78d)

**Comment by jzongker** [comment]
@Bagel94 - Sorry, this is getting embarrassing.  

It should be working now.  We do weekly deploys on all the apps early Monday morning.  In this one was an unrelated improvement to the login pages across all the apps, to return you to the exact url you were on after login instead of the home page of each app.  That redirect wasn't handling query strings properly which broke this oauth form.  It's fixed now.

**Comment by Bagel94** [comment]
@jzongker no worries! I get it lol. I had to redo our chum's stuff, because I messed up and deleted my account and had to have everything deleted so I could start over.

With that though, it looks like all (or at least the majority) of the songs are now syncing to Chums! Even the ones that were giving us problems!!

Thanks for all your work!!
