### ISSUE TITLE
MacMini M4 - Local Network Name Already in Use error

### ISSUE THREAD

**Issue by Mark-SoundEngineer** [ChurchApps/FreeShow#1637]
Whenever 'RemoteShow' or 'StageShow' are enabled in Settings: Connections, the 'Network Name is Already in Use' error appears when the Freeshow is started. Every time.

Turning off these two options, prevents the error. After the error is accepted your mac local network make is changed (higher number added).

MacMini M4 Sequoia
 - FreeShow Version: V1.4.2 and V1.4.3

'RemoteShow' or 'StageShow' still work, but the operator has to clear the error each time the app is opened. The issues on different networks, but only on a Mac. A PC on the same network does not have the same issue.

Ideas??

**Comment by Mark-SoundEngineer** [comment]
![Image](https://github.com/user-attachments/assets/b8fa3f30-ceb0-4b15-8789-ecbbc2bb131b)

**Comment by armm29393** [comment]
Same with Macbook Air M2

**Comment by vassbo** [comment]
That has happen to many mac users lately.

@Auxority Do you think it's caused by a package update?: https://github.com/ChurchApps/FreeShow/pull/1529

**Comment by vassbo** [comment]
Got it. But it did not happen previously, only the last few weeks.

**Comment by andrewgribben** [comment]
Yes it's definitely a recent occurence. I feel like there's some interplay between NDI, Bonjour and how the computer is advertised on the localnetwork

**Comment by Auxority** [comment]
@vassbo we can always try to revert it locally and see what happens.

**Comment by vassbo** [comment]
I don't have a mac, so I can't test it.

**Comment by Auxority** [comment]
Ahh alright, then I’ll try later this week.

**Comment by Mark-SoundEngineer** [comment]
> Have you tried to change the port number? Maybe add a 1 to the end of the port number, so 5510 becomes 55101.
> Gear icon->Connection->RemoteShow->Gear Icon->Port Gear icon->Connection->StageShow->Gear Icon->Port

I tried the above suggestion, but no joy I'm afraid.

**Comment by vassbo** [comment]
@Mark-SoundEngineer What if you go back to FreeShow version 1.4.0, does that version not have this issue?

**Comment by Auxority** [comment]
I experienced the same issue on 1.4.3 

![Image](https://github.com/user-attachments/assets/ffde5521-3064-4c4b-bcd8-3a7d11889b26)

**Comment by vassbo** [comment]
Okay, if you encounter it more, whould you like to try and revert some packages to find out what is causing it? Because it did not happen previously. It breaks NDI outputs temporarily, but it does not look like it's a very big deal.

**Comment by Auxority** [comment]
Nope, tried everything I could but cannot replicate the issue. It only happened after the update, but has not happened since. I have installed Freeshow through Homebrew, maybe that could be the difference. Let me try something..

**Comment by Mark-SoundEngineer** [comment]
Hi Guys. Thanks for persisting on this. I have done some research/testing, that I hope might prove useful to you:

I did a clean install of FS 1.4.3 on a different Mac Mini (M2 Pro, OS 15.3. 2), on a different network. Immediately got the local host name error. Restarted the Mac and still always get the error with StageShow turned on. The only thing I found to stop this was turning off Local Network Access permission in Mac settings (as you would expect).

I did a clean install of FS 1.4.0 on the same Mac and did NOT get the error, even after restarts, and StageShow still works (with Local Network Access permission set to on).

I enabled an auto update to FS 1.4.3 and the error reoccurred on the updated version. Though it errors only the first time FS was opened after a restart. But does so after every restart.

I tried opening the error log under Connections, Other, but it said "This does not exist!". On a PC I do get an error log... but this problem does not exhibit on a Win PC.

Helpful?

**Comment by Auxority** [comment]
@Mark-SoundEngineer I did some further tests, I cannot replicate your issue. But I have found another issue. Sometimes I cannot delete projects. I'm trying different versions (tags) right now to pinpoint the issue.

**Comment by Auxority** [comment]
<img width="1800" alt="Image" src="https://github.com/user-attachments/assets/1b3ff4ed-7779-4f44-b5f5-448ac11d08f9" />
The issue I mentioned was introduced in 1.4.2. Let's see what the culprit is.

**Comment by vassbo** [comment]
Thanks. I got that freeze fixed it happened when there was no project opened.

**Comment by Mark-SoundEngineer** [comment]
Hi Guys. I'm about to do my 4th installation of FS onto a MacMini and just wondered if there was a way to avoid the 'local host name' conflict/change that occurs if you turn on any remote options under connections? (other than rolling back to v 1.4.0)

Thanks very much.

**Comment by Auxority** [comment]
@vassbo Maybe we can try to update the minor versions of packages again. If that doesn’t help we can always revert it.

**Comment by vassbo** [comment]
Would you like to do that?

**Comment by Auxority** [comment]
Sure, will try to do that tomorrow.

**Comment by frederickjh** [comment]
I too am seeing this on a new iMac, but as others have stated I do not believe this is related to FreeShow code directly.

apple.stackexchange.com has the question that is currently 11 years and 3 months old : [How do I stop my computer name from automatically, and incorrectly, changing?](https://apple.stackexchange.com/questions/125411/how-do-i-stop-my-computer-name-from-automatically-and-incorrectly-changing)  

In the answers some surmise that the automatic network configuration (aka on other OSes ) mDNS /  Bonjour / Avahi / Zero-conf Networking is to blame. Others say that using multiple network devices at the same time is an issue too. A number of solutions are given, some say they work others say they do not.

It is a good read and maybe if enough of us try the solutions put forth we can find one or more that work to solve this.

**Comment by frederickjh** [comment]
@Auxority have you ever gotten a chance to work on this? 
@vassbo  I think that this issue should be reopened.  I have changed my opinion that this is a FreeShow bug. Ever time I start FreeShow I get this message and must then go in to OBS Studio and change the NDI inputs to the new ones with the new hostname. This is very annoying and one day I am going to forget and not have my lower thirds and overlays in OBS Studio at service time.

Is it possible that it maybe solvable outside of FreeShow? I believe yes but not everyone is a network guru that can set IP reservations for MAC addresses and some maybe do not have access to do so. I believe that setting an IP reservation for computer that FreeShow is on with the hostname in the DHCP server would fix this.

**Comment by Auxority** [comment]
Sorry I completely forgot to try the minor version upgrade.

**Comment by thebiblelover7** [comment]
I believe this is not a FreeShow issue at all as we were having this issue on Mac OS, even when we were using ProPresenter. It seemed to be a network misconfiguration, and something about improper shutdown.

**Comment by frederickjh** [comment]
@thebiblelover7  FreeShow is the only program on the iMac that we have that every time you open it the message appears. Even the test version of ProPresenter does not make the message appear that the computers local hostname has changed. 

I am sure there are other programs that will cause this to happen too but with FreeShow it happens every time the program starts. We are shutting down the iMac using the shutdown from the Apple menu.

The fact that it did not do this in past versions as @Mark-SoundEngineer determined that in version previous to 1.4.0 it did not do this, points to the fact that something in FreeShow was introduced in the code before the next release.

**Comment by thebiblelover7** [comment]
@frederickjh okay, that makes sense... Our issue had to deal with macOS itself, and not FreeShow showing this error. Sorry, I misunderstood.

It's still weird for FreeShow to show this error though. I hope we can get this fixed soon :).

**Comment by vassbo** [comment]
We updated some dependencies if someone wants to see if it's fixed or not: https://github.com/ChurchApps/FreeShow/releases/tag/v1.4.9-beta.2

**Comment by frederickjh** [comment]
> We updated some dependencies if someone wants to see if it's fixed or not: https://github.com/ChurchApps/FreeShow/releases/tag/v1.4.9-beta.2

@vassbo I tested this beta at the church for #1957 on Thursday. I switched back to 1.4.8 but I did notice today that I did not have the popup about the hostname changing even though I was using the stable version. NDI outputs in OBS Studio were working and did not need to be changed to the new host name.

I will test the beta when I am next at the church.

**Comment by frederickjh** [comment]
> [@frederickjh](https://github.com/frederickjh) okay, that makes sense... Our issue had to deal with macOS itself, and not FreeShow showing this error. Sorry, I misunderstood.
> 
> It's still weird for FreeShow to show this error though. I hope we can get this fixed soon :).

@thebiblelover7 Sorry, I think you misunderstood me. The error is shown by the MacOS not by FreeShow. However, it seems to be triggered by FreeShow starting as the popup appears almost immediately every time after FreeShow starts.

**Comment by vassbo** [comment]
Seemingly it was caused by this: https://github.com/ChurchApps/FreeShow/blob/main/src/electron/data/bonjour.ts
Which means it should be fixed in 1.4.9 I hope.

**Comment by vassbo** [comment]
If anyone would like to test: https://github.com/ChurchApps/FreeShow/releases/tag/v1.4.9-beta.3

**Comment by frederickjh** [comment]
@vassbo I tested this today with 1.4.9-beta.3 and still no popups. I have not had a popup about the local network name already in use since I ran the 1.4.9-beta.2 to test something else. Even when I went back to running 1.4.8 on Sunday.

**Comment by Mark-SoundEngineer** [comment]
Sorry to say that I still get this error (if any remotes are turned ON in connections), but now only once after each MAC restart. Running Version 1.4.9 on Mac Mini. (Does not repeat the error after 'sleep', just after full restart.)

**Comment by frederickjh** [comment]
I will have to test the remotes turned on here to see if that also triggers it on an iMac with MacOS 15.

**Comment by frederickjh** [comment]
@vassbo I think we need to reopen this issue. 

I see I dropped the ball and never tested the remote connections after @Mark-SoundEngineer said he was still having issues.  I recently learned of the FreeShow Remote app and to use it turned on the **Control Show** under connections in the settings and noticed that these messages have returned as well as the hostname being changed every time I restart FreeShow. I then tried to figure out which ones make the message (From MacOS) pop up when FreeShow starts.

They all do,  **Remote Show**, **Stage Show**, **Control Show**, **Output Show**. Only the **API** connection does not cause MacOS to popup the message that hostname is in use and has been changed. Not sure if that is a help in tracking it down but it is the one connection that does not cause these messages to popup.

Would a error log from the iMac be of any help to diagnose this? 
I am willing to help test fixes for this. Just let me know.

I would like to use the **Control Show** with the FreeShow Remote app but with it on I have to remember each time I start FreeShow because the change in hostname changes the name of all the NDI outputs on the computer to go into OBS Studio and fix those sources. Which is just one more thing to do on a busy Sunday morning. I see this has also come up recently in #3058

**Comment by vassbo** [comment]
Do you have the same issue in the latest version (1.6.0-beta.3) as well?

**Comment by frederickjh** [comment]
Sorry @vassbo did you work on a fix for this recently? I only tested on 1.5.9. this past Sunday.

**Comment by frederickjh** [comment]
@vassbo  tested this on the 1.6.0-beta.3 and MacOS still popped up the hostname in use dialog as soon as I started FreeShow. This was with Control Show enabled.

**Comment by vassbo** [comment]
Okay, the change I made did not help then. I'll have to try to recreate this.

**Comment by vassbo** [comment]
I might have gotten this fixed now, I think fixing this issue previously introduced another related issue.

**Comment by frederickjh** [comment]
@vassbo I tested this on 1.6.0-beta.4 and it did not fix the issue for me I still had the issue of MacOS popping up the hostname changed dialog box. However, I think I may have found a work around to switching the FreeShow NDI source(s) in other programs.

I use the NDI Video Monitor from NDI Tools. NDI uses the hostname in the NDI sources. I noticed that my NDI sources on the same Mac were coming from different hostnames. I also checked MacOS setting to see what the hostname was set to and in a terminal with hostname. Note that in these screenshots there is one computer other than the Mac that is acting as a NDI source.

In this screenshot FreeShow is using a hostname with "-3" on the end for its NDI source hostname.

<img width="555" height="131" alt="Image" src="https://github.com/user-attachments/assets/047bd0a4-713f-4632-9656-7918da8f60b5" />

Above it, in the screenshots, you can see OBS Studio is using a hostname with "-2" on it. Presumably what the computer started with, but lower down in the screen shot you see the MacOS setting showing a hostname with "-4" on it. I checked in the terminal and the 'hostname' command reported back that the hostname had a "-3" on it. Not sure if this information help to solve this somehow but it does seem strange that the OS settings already have the "next" hostname and not the current one.

<img width="732" height="813" alt="Image" src="https://github.com/user-attachments/assets/037d7e67-1e2e-4e80-a392-f948e6287ccc" />

Now to the workaround. Since FreeShow only seems trigger a change in hostname once each time the computer is restarted. I figured out that in the MacOS settings > Sharing > then scroll to the bottom you can click the edit button and set the hostname (shown in the second screenshot above). 

I first closed and programs that act as an NDI source like FreeShow and OBS Studio. I then edit the hostname. I just removed the  dash and the number at the end. After restarting the NDI source programs NDI Video Monitor looks like this with all NDI source coming from the name hostname.

<img width="584" height="133" alt="Image" src="https://github.com/user-attachments/assets/1a8c51be-126b-4a11-b0c6-645c722fd163" />

**Comment by vassbo** [comment]
@frederickjh Oh, nice. Glad you found a workaround!
It still might have been fixed in 1.6.0, but if not this must be the cause and solution.

**Comment by frederickjh** [comment]
@vassbo I have not had a chance to test this on 1.6.0 (other issues that I had to down grade to 1.5.9 to fix). Very curious to know, do you release code into a stable release that has not been released into a beta version first for testing? As, I tested this on the last beta release before the stable release.

However,  I think you are missing something important here. The Mac boots up and get a hostname. FreeShow starts and the hostname changes to the next dash number hostname but the Mac settings are reporting the future hostname that will be next one used. The command line command `hostname` gets the correct current hostname. I think fixing this is just a matter of where FreeShow gets the hostname from (if it is possible to change that). I think that FreeShow is getting it from the OS and it is reporting it wrong (the future hostname). Not sure if you can use the comand line command `hostname` to get it.

**Comment by frederickjh** [comment]
I tested this in 1.6.0 @vassbo and still get the MacOS popup about the hostname changing. One note to anyone using the work around I suggested above, make sure that after editing the hostname to hit Return / Enter to save it. Just exiting the filed does not seem to change hostname. Running `hostname` in a terminal will show you what your current hostname is.

Another method for changing the hostname is to run the following in a terminal `sudo hostname my-macs-hostname`. This would set the hostname to **my-macs-hostname**. Just change that to what you want the hostname to be. You will also need to enter your password to do this since you are using sudo to get root privileges.

**Comment by benbaptist** [comment]
Indeed, @frederickjh, I just encountered this issue on my system running `1.6.0` as well. I hadn't seen it in a while so I figured it had been resolved a while ago, but it managed to increment my hostname to a suffix of `-8` in the matter of seconds. I don't use NDI but I do have RemoteShow & StageShow enabled. It's just occuring to me that I almost never utilize those, so I guess I'll turn them off for now. Super weird stuff! I'm running macOS 26.0.1 for what it's worth; yeah, I know, I gotta update hahah.

**Comment by frederickjh** [comment]
@benbaptist we are still using macOS 15, but this seems to be an ongoing issues that I am not sure if all the blame can be put on the programs or if some of it is on the OS that auto renames the hostname.

@vassbo I tested this on 1.6.1-beta.1 and right after the reboot we still get a popup that the hostname has been changed.
I am also looking into different proposed "solutions" to fixing this issue. I will get back to you if there is one that fixes this.

**Comment by vassbo** [comment]
Update: https://github.com/ChurchApps/FreeShow/releases/tag/v1.6.1-beta.2

**Comment by frederickjh** [comment]
@vassbo I tested this on 1.6.1-beta.2 and 1.6.1-beta.3 and the popups do not appear shortly after starting. 

However, I have been trying to figure out if the fault is also with the MacOS settings and recently used the command line to set Hostname, ComputerName and LocalHostname all the same. Not sure if that makes any difference, but some said the duplicate hostname message may be cause by it checking one that was set differently.

**Comment by frederickjh** [comment]
I tested this on 1.6.1 and still no popups.

I made some changes to hostname setting before 1.6.1-beta.2 came out. I say this in case the fix was not in FreeShow code but in the settings I changed.

I opened a terminal and set `ComputerName`, `HostName`, and `LocalHostName` to the same thing. How to do this is outlined in this OSX Daily help article [How to Set the HostName, Computer Name, and Bonjour Name Separately in Mac OS X](https://osxdaily.com/2012/10/24/set-the-hostname-computer-name-and-bonjour-name-separately-in-os-x/)

Here is a brief recap using **MyHostname** as the ComputerName/Hostname/LocalHostname

#### Check what the `ComputerName`, `HostName`, and `LocalHostName`  are set to

```bash
# Getting the host name:
sudo scutil --get HostName

#Getting the computer name:
sudo scutil --get ComputerName

#Getting the Bonjour local host name:
sudo scutil --get LocalHostName
```

#### Set the `ComputerName`, `HostName`, and `LocalHostName`  to "MyHostname"

```bash
# Set the hostname
sudo scutil --set HostName "MyHostname"

# Set the computername
sudo scutil --set ComputerName "MyHostname"

# Set the localhost name
sudo scutil --set LocalHostName "MyHostname"
```

One other tip the HostName can also be checked without `sudo` by running the `hostname` command in a terminal.

Since I have set these all the same, I have not seen them change (Yah, no more NDI sources changing names in OBS Studio). No dashes with numbers added to the end of the hostname by MacOS. I guess only time will tell if these change made the issue go away or the code changes (Thanks @vassbo !).
