### ISSUE TITLE
Bible reference is using english book names instead of localized names

### ISSUE THREAD

**Issue by danielbanjan** [ChurchApps/FreeShow#2300]
**Describe the bug**
Bible reference is using english book names instead of localized names

**Reproducing**
Import a bible that is not english
Search using reference.

**Screenshots (Optional)**
<img width="1859" height="421" alt="Image" src="https://github.com/user-attachments/assets/0443184c-e9ac-4135-90b9-7986097c55e3" />

**Version (Optional)**
 - OS: Windows
 - FreeShow Version: 1.5.1

**Additional context**
[Biblia Romana VDC 1928.txt](https://github.com/user-attachments/files/23289160/Biblia.Romana.VDC.1928.txt)

**Comment by danielbanjan** [comment]
I attached the .fsb file as .txt since .fsb is not allowed to be uploaded here, you can try to go to Iuda 1:5 for instance and you'll see it's going to Judecatori 1:3 instead, something's not working right.

<img width="1883" height="402" alt="Image" src="https://github.com/user-attachments/assets/a992a048-e41d-4825-be53-0aa76bc3e6ed" />

**Comment by Domus3** [comment]
I have the same problem. I also report that if I search for a verse in a Bible in another language, not only the Bible book names are in English, but the chapter and verse numbers are not recognized. Each book remains stuck on the first chapter and the first verse (1:1).

<img width="2368" height="486" alt="Image" src="https://github.com/user-attachments/assets/14fedbaf-4689-4a44-be3b-25b10e6e39f9" />

**Comment by Domus3** [comment]
I would also point out that I have tested several versions, and that these problems begin to occur starting with version 1.5.1-beta.2.

Everything works correctly using version 1.5.1-beta.1.

**Comment by yurividal** [comment]
I believe this is related to [this](https://github.com/ChurchApps/FreeShow/issues/2275#issuecomment-3455935376)

If so, it should be fixed for the next release

**Comment by vassbo** [comment]
The strange thing is all the Bibles I tested with non-English names worked fine. I think the problem is when the three first letters matches the English abbreviation, but it should have still shown the translated name. But I'll investigate.

**Comment by danielbanjan** [comment]
> The strange thing is all the Bibles I tested with non-English names worked fine. I think the problem is when the three first letters matches the English abbreviation, but it should have still shown the translated name. But I'll investigate.

Also is it normal even when you manually go and select ( with click and such ) for the scripture to show the current selection in the bottom left in english? Maybe related, not sure.

**Comment by vassbo** [comment]
@danielbanjan Thanks for the Bible file, I got it fixed! The problem was that the book number was supposed to be a number, but it was a string, so it didn't find the book.

**Comment by danielbanjan** [comment]
So I can fix this myself if I adjust the file to use ints for book nr and chapter number and such?

**Comment by vassbo** [comment]
Yep, but there should be a beta out later today with the fix.

**Comment by danielbanjan** [comment]
> Yep, but there should be a beta out later today with the fix.

perfect, thanks so much!

**Comment by vassbo** [comment]
https://github.com/ChurchApps/FreeShow/releases/tag/v1.5.2-beta.1
