### ISSUE TITLE
FreeShow sometimes fails to start up properly

### ISSUE THREAD

**Issue by yurividal** [ChurchApps/FreeShow#2595]
I've been experiencing this issue since quite a few versions back, and it is still present in 1.5.5

Windows 11.  My data location is set to the default (user\Documents\FreeShow)

Sometimes, when we open FreeShow, it feels a bit slow, and when this happens, we are unable to load any shows, or scriptures. It just spins forever, on the project list panel, and on the main panel. 
The sollution is to kill freeshow from the task manager, and re-launch it 

Error log json doesn't show any errors, and I still haven't been able to identify exactly what needs to happen for the issue to appear. It seems pretty random to me. 

I've seen at least one user rerport this of facebook too. 

What can i do to try to troubleshoot this? Is this a known issue?

**Comment by vassbo** [comment]
Can you try to recreate this with the console to see if there's any errors there? I have not encountered this myself.

**Comment by yurividal** [comment]
Yeah, I don't think I've ever been able to reproduce it on my dev machine. 
But it happens quite often on the church computer. I don't have the console environment setup over there.

**Comment by vassbo** [comment]
Installing as administrator might help if it's a permission issue.

**Comment by vassbo** [comment]
You can try running from the command line as well sometime and let me know if there's any errors there.

**Comment by Michael-MRC** [comment]
This sounds exactly the same as the issue I have, where it just spins for an extremely long period of time. I always end up force quitting and opening again. This happens the first launch of FreeShow every day it's used.

I also haven't been able to reproduce it at home, on a virtually identical build machine.

**Comment by vassbo** [comment]
Thanks. I would like to fix this, but it's hard to recreate.

**Comment by vassbo** [comment]
Can this be related to auto backup or any cloud syncing or planning center fetching?

**Comment by yurividal** [comment]
I don't have any cloud features enabled

**Comment by vassbo** [comment]
What about the auto backup?

**Comment by yurividal** [comment]
Yes, I have weekly auto backup enabled.

**Comment by vassbo** [comment]
Do you think it can be related to that or not?

**Comment by yurividal** [comment]
Hum.... This would make sense, and probably explain why it only seems to happen once in a while. Perhaps once a week... 
I'll try to enable daily backups on my test computer, and see how it behaves for a few days

**Comment by vassbo** [comment]
I just fixed a few issues where it tried to load too many and too large files into memory, so it might as well be fixed on the dev branch, not sure. (Or it might have the fix on the cloud branch only atm)

**Comment by vassbo** [comment]
Let me know if this is still an issue after the latest version: https://github.com/ChurchApps/FreeShow/releases/tag/v1.5.6-beta.2

**Comment by yurividal** [comment]
Hi @vassbo this is still an issue for me on 1.5.6
Its always on the first launch of the day (but not every day).

FreeShow loads, but when you try to go to any projects, its says can't find any shows. Go to scripture, and the scriptures just spin loading forever.


I launched Freeshow from the command line, as you suggested, but i don't seem to see anything too obvious:
````
C:\Users\user>
Starting FreeShow...
REMOTE on: 5510
CONTROLLER on: 5512
OUTPUT_STREAM on: 5513
NDI - creating sender: FreeShow NDI - OBS
REST: Listening for data at port 5506
WebSocket: Starting server at port 5505
OSC: Listening for data at port 5505
WebSocket: Client connected.
WebSocket: Received action toggle_log_song_usage
WebSocket: Received action toggle_log_song_usage
(node:12848) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 MAIN listeners added to [IpcMainImpl]. MaxListeners is 10. Use emitter.setMaxListeners() to increase limit
(Use `FreeShow --trace-warnings ...` to show where the warning was created)
WebSocket: Received action toggle_log_song_usage
WebSocket: Received action toggle_log_song_usage
WebSocket: Client disconnected.
WebSocket: Client connected.
WebSocket: Received action toggle_log_song_usage
WebSocket: Received action toggle_log_song_usage
(node:12848) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 MAIN listeners added to [IpcMainImpl]. MaxListeners is 10. Use emitter.setMaxListeners() to increase limit
WebSocket: Received action toggle_log_song_usage
WebSocket: Received action toggle_log_song_usage
````


**I noticed that if i just forget, and leave freeshow trying to load, after like 2 minutes it eventually starts working...** 
But if i kill the app, and relaunch it, it works perfectly, immediately

**Comment by vassbo** [comment]
I think it's related to the backup?

**Comment by yurividal** [comment]
it could be.. but the logs i just sent you are from my church PC, where i have auto-backup set for weekly, on mondays. And, it seems to happen more than once this week. 

On my test/dev device, i have auto-backup set to daily. The issue has happened a few times, but i didn't manage to capture any console logs here.

**Comment by vassbo** [comment]
Thanks. I'll have to look more into it, I havent had this issue myself, which is strange.

**Comment by Michael-MRC** [comment]
For what it's worth, I have auto backup set to weekly, but this seems more like a daily issue.

I've resigned myself to the fact that we just always restart FreeShow after first attempt of the day. 

I will try replicate the issue on my home PC, but it's very hard to do that when it's only a once a day issue at best.

**Comment by yurividal** [comment]
@vassbo perhaps it might be useful for the next beta build to have more verbose loging, to help identify this?

**Comment by vassbo** [comment]
Does this still happen in 1.5.7?

**Comment by yurividal** [comment]
Yes, unfortunately it does, mate.

Just had it happen basically every day last week. It's always on the first launch of the day, or when Freeshow is closed for a long time.
My team already knows to default to always killing the app at the first sign of freezing when they launch the app in the morning.

**Comment by vassbo** [comment]
And you are not able to recreate on the dev machine? Maybe you can backup the church PC data and use that..

**Comment by vassbo** [comment]
I have yet to experience this myself... So it might be something with a specific configuration

**Comment by yurividal** [comment]
I'm not able to replicate it on my dev machine.
I use the same configs from my church PC. Only difference is no NDI. Could that be the issue? Hum....

**Comment by vassbo** [comment]
If that's the only difference it seems likely, I don't have NDI on either..

**Comment by vassbo** [comment]
Please try: https://github.com/ChurchApps/FreeShow/releases/tag/v1.5.8

**Comment by yurividal** [comment]
> Please try: https://github.com/ChurchApps/FreeShow/releases/tag/v1.5.8

Just installed 1.5.8 o the church PC. Then, launched it...

<img width="1727" height="768" alt="Image" src="https://github.com/user-attachments/assets/99ccacce-38d8-4c8e-9d03-98486c670756" />

Still same thing... i killed freeshow, and re-launched it, and then it works fine.

Do you want to compile a special test version with extra verbose logging, so that we can try to understand this once and for all?

**Comment by vassbo** [comment]
Okay, I'm not sure what to log. You should be able compile it as well..

Temporarily remove `azureSignOptions` from `electron-builder.yaml`
Run `npm run release` on Windows to get a .exe file.

**Comment by vassbo** [comment]
So it's loading for a long time, but you can navigate the app tabs still?

**Comment by yurividal** [comment]
Thanks, I'll give it a go...

**Comment by yurividal** [comment]
> So it's loading for a long time, but you can navigate the app tabs still?

Yes, you can navigate the app, but bibles, shows, songs etc nothing loads. It just spins for ages. 
I think if you let it sit there for a few minutes, it loads the song, but takes forever

**Comment by vassbo** [comment]
That certainly means something is blocking the main thread, because the shows loading has a hardcoded limit of 8 seconds, and the rest (projects/scriptures) should just take a couple ms max. But the fact that it's loading at all, should mean that it has received the initial data.

**Comment by yurividal** [comment]
Just fyi, this is still present in 1.5.9

**Comment by vassbo** [comment]
Yep, thought so. I still don't have a way to reproduce.
If we could reproduce it consistently, we could find out what version it started in..

**Comment by Michael-MRC** [comment]
I was never able to replicate this at home, despite creating a backup and having a near identical setup at home (same hardware expect the GPU, same version of windows 11 etc). 

I finally had time (first day off this month), to actually uninstall 1.5.5, and reinstall it, then restore the backup, and I've noticed an immediate performance improvement clicking through shows.  I'll have to wait until tomorrow to see if my daily freeze issue has gone away.

**Comment by Michael-MRC** [comment]
Sadly, the issue still exists, and the smooth running only happened for a day, now it's back to how it was.  Could it be something to do with OneDrive?  Our media tends to be pulled from a Documents folder that is synced with OneDrive.. just a wild thought. There doesn't seem to be a consistent pattern though, I have PNG files that were dropped into a show, and when that show is opened, some load instantly and others take a few seconds to appear, but they are the same size PNGs in the same folder.

**Comment by yurividal** [comment]
> Sadly, the issue still exists, and the smooth running only happened for a day, now it's back to how it was. Could it be something to do with OneDrive? Our media tends to be pulled from a Documents folder that is synced with OneDrive.. just a wild thought. There doesn't seem to be a consistent pattern though, I have PNG files that were dropped into a show, and when that show is opened, some load instantly and others take a few seconds to appear, but they are the same size PNGs in the same folder.

Don't think it's one Drive. 
We don't use oneDrive, and we also have all our files in the default documents folder. Yet, every morning, once per day, freeshow fails to start up properly. My team already knows, they just open freeshow, wait a few seconds, kill it, then open again.

**Comment by yurividal** [comment]
I just wish there was a way to see the logs of what is happening. Unfortunately, nothing is printed to the console nor to the json log file

**Comment by vassbo** [comment]
What about 1.6.0-beta.3, has it happened in that version, yet? I made some NDI changes if that has anything to do with it.

**Comment by vassbo** [comment]
Or what if it's some old configuration, but I still don't get why it fixes itself on the second load.

**Comment by yurividal** [comment]
I'll try beta3 on the church PC this week, and I'll let you know

**Comment by yurividal** [comment]
Just installed beta 3, without launching 1.5.9 this morning on the church PC.

Again, upon launch, Freeshow freezes right after I press YES on the admin question. 

<img width="51" height="51" alt="Image" src="https://github.com/user-attachments/assets/6b28e14d-ecdb-4b9e-8fa4-d1aebe96582d" />

After force-closing and launching again, it works as intended.

**Comment by tobsowo** [comment]
I'm experiencing the Scripture taking time to load making it hard to display the Bible text as at when the preacher mentioned it and also double clicking on a verse to show immediately on the screen takes time to apply too.

Using 1.6.0.

**Comment by vassbo** [comment]
@tobsowo See this: https://github.com/ChurchApps/FreeShow/issues/2807

**Comment by tobsowo** [comment]
@vassbo seen and I'm experiencing same as mentioned regarding the scripture loading. All Bible are important locally into FreeShow and nothing have to do with online Bible.

**Comment by nabsac** [comment]
Yurividal, you said, 
"I don't think I've ever been able to reproduce it on my dev machine.
But it happens quite often on the church computer."

So I am guessing it is (A) config issue or  (B) problem file in Document/freeshow directory on the church PC.

(A) Try deleting the freeshow folder at C:\Users\user_on_your_pc\AppData\Roaming?
1. Backup freeshow in the app.
2. Uninstall freeshow.
3. Delete freeshow folder in directory C:\Users\user_on_your_pc\AppData\Roaming?
4. Restart PC.
5. Install updated version of freeshow.

B) Check for problem file in Document/freeshow directory
1. Ensure that there are no file types in your freeshow directory that was not created by freeshow. So delete docx, pptx, and anything you think does not belong. Then fully shut down PC and restart freeshow.
2. If there is still loading issue copy Document/freeshow folder with content to your dev machine.
If it loads fine on dev machine, then you my need to re-install the OS on church pc to fix the issue.
3. If there is a problem with loading on dev pc (which did not exist before), then the issue is inside Document/freeshow folder.  Delete some files from that directory bibles, videos, shows, images. Restart pc and observe load time after each set of deletion.

I wish you luck and hope you resolve the issue.

**Comment by jzongker** [comment]
I think this may be a slow disk issue.  Does the church computer have a magnetic HDD rather than a SSD?  And quite a few shows?  

On a HDD each show file is going to take tens to hundreds of milliseconds to be read, plus are likely being scanned by Windows Defender.  On the second launch they're in the disk cache and Defender's scanned cache.  If you're able to move the data to a SSD I'd imagine that would solve it.

Another contributing factor could be the auto backup starting 2 seconds after launch and trying to read the same files.  Delaying that until everything is loaded would probably cut the load time in half.

**Comment by yurividal** [comment]
Hum... This makes sense... I do have more than 3000 songs in our database. 
I have auto backup off.
I can't remember if the church has HDD or SSD. I'll check tomorrow

**Comment by Michael-MRC** [comment]
> I think this may be a slow disk issue. Does the church computer have a magnetic HDD rather than a SSD? And quite a few shows?
> 

Not an HDD issue, as ours is definitely decent SSD/NVMe drives. 
It's only the first load each day, and you could kill FS in an instant after startup, and reopen it will be perfectly fine.

Good thought though.  I'm still trying to replicate it on a virtually identical machine at home.

If any one has been running Windows 10 on an SSD, they are a very patient person. I doubt Windows 11 is any better. So much multi-tasking on modern OS's that an HDD for the OS doesn't stand a chance.

**Comment by MyGuyConsultingYou** [comment]
I have the same issue of having to force quite my initial FreeShow startup becuase it freezes at the "admin" button on a Macbook Pro M1 Pro v.1.6.1

1. I had a few profiles setup and just deleted them and will try to recreate and record tomorrow. 
2. No cloud sync active
3. Connected to APlay
4. Daily backup
5. Autosave 15min
6. 1TB SSD

**Comment by Michael-MRC** [comment]
Does anyone else leave their PC running 24/7 (without FreeShow running). I'm still trying to think of differences between my church setup and home. At home, I don't leave my PC on day and night, but our vision PC at church is left on always, so it can be remote accessed etc.

@MyGuyConsultingYou I've never set up additional profiles.

**Comment by yurividal** [comment]
> Does anyone else leave their PC running 24/7 (without FreeShow running). I'm still trying to think of differences between my church setup and home. At home, I don't leave my PC on day and night, but our vision PC at church is left on always, so it can be remote accessed etc.
> 
> [@MyGuyConsultingYou](https://github.com/MyGuyConsultingYou) I've never set up additional profiles.

Yes, my church computer where we see this issue is left on 24/7 too

**Comment by vassbo** [comment]
Let me know if this is still an issue in 1.6.3.

**Comment by yurividal** [comment]
Sorry, I have been away for many weeks due to work, and have been holding back on upgrading until I was back.
I just installed 1.6.4 last week, and this issue still persists, unfortunately.

**Comment by yurividal** [comment]
@vassbo sorry, maybe consider reopening this issue?

**Comment by vassbo** [comment]
@yurividal Not sure what I can do about it at this point.
