### ISSUE TITLE
media flashes

### ISSUE THREAD

**Issue by Prezib** [ChurchApps/FreeShow#341]
Hi, I had raised this earlier and you advised it was the transition which I have now checked and it still flashes despite being none. Not sure if there is anything else I am doing wrong
[FreeShow 2023-12-18 18-10-22.zip](https://github.com/ChurchApps/FreeShow/files/13707119/FreeShow.2023-12-18.18-10-22.zip)

**Comment by vassbo** [comment]
Okay, I'll take a look.

**Comment by vassbo** [comment]
This should work now if the main transition is set to "none", instead of the "item transition".

**Comment by Prezib** [comment]
Still happening with both item and the main transition set to none.

**Comment by vassbo** [comment]
Just setting the main "**Text** transition" to "None" works for me.

**Comment by Prezib** [comment]
this is what I
[WhatsApp Video 2024-01-04 at 00.07.52_3d3ee48b.zip](https://github.com/ChurchApps/FreeShow/files/13824549/WhatsApp.Video.2024-01-04.at.00.07.52_3d3ee48b.zip)
 see when I do that

**Comment by vassbo** [comment]
It should be better now, it might still flash because the image is loaded again when changing slides. But I have to redo the whole transition system to fix that.
